### ISSUE TITLE
game_canvas_1

### ISSUE THREAD

**Issue by DigitalMacros** [natalivb/urok5#2]
Здравствуйте.
1. Радиусы шариков.
    ball_maximal_radius = ent1.get()
    ball_maximal_radius = int(ball_maximal_radius)
    эти строки можно объединить в одну
    ball_maximal_radius = int(ent1.get())

```
Думаю, следует поставить защиту от дурака. Т.к. Вы указываете интервалы радиусов, то желательно поставить проверку на корректность ввода данных.
Может быть стоит указать дефолтовые значения радиусов в начале игры и (или) в случае некорректного ввода.
```
1. Движение шариков.
   Некоторые шарики выходят за границы игрового поля. Попробуйте это устранить.
2. Общая организация кода.
   Большой разброс. То идёт описание функции, то следует значение глобальной переменной. Попробуйте всё упорядочить.
   Название виджетов лучше давать интуитивно понятными. Т.к. когда встречаешь в коде кнопку but1 не понятно для чего она.

**Comment by natalivb** [comment]
Осталось разобраться с защитой от дурака

**Comment by DigitalMacros** [comment]
Здравствуйте, Наталья.
После выполнения, закрывайте запрос. Так мне проще будет отслеживать Вашу деятельность.
В общем вполне хорошая работа.

**Comment by natalivb** [comment]
Спасибо!
