### ISSUE TITLE
Игра "Пушка"

### ISSUE THREAD

**Issue by DigitalMacros** [natalivb/urok5#4]
Здравствуйте, Наталья.
Не нашёл Вашего вклада в игре "Пушка"

**Comment by natalivb** [comment]
Здравствуйте, Сергей! Над пушкой я подумаю после 1 августа, на горячих источниках, увы, нет компьютера.

**Comment by DigitalMacros** [comment]
Здравствуйте, Наталья.
Полагаю Вы на отдыхе (или были там).
Подключайтесь к работе.

**Comment by natalivb** [comment]
Здравствуйте, Сергей.
Отдых не отпускает. К работе подключилась, но получается ерунда.
